// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3nHrfKfOwsg3MTUnUgR_wzU_dp-wekVE',
    appId: '1:74155828355:web:16c4d58524019c9764a7b6',
    messagingSenderId: '74155828355',
    projectId: 'dalel-e9613',
    authDomain: 'dalel-e9613.firebaseapp.com',
    storageBucket: 'dalel-e9613.appspot.com',
    measurementId: 'G-TJKHE0VYNN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA53WQy2YBIpwcIP_q6756XHeI0bodSwiE',
    appId: '1:74155828355:android:5cf85e7dd5ca9f3f64a7b6',
    messagingSenderId: '74155828355',
    projectId: 'dalel-e9613',
    storageBucket: 'dalel-e9613.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpdDAdmOj08eh7jvEgOZ1U_1eofUXkbX0',
    appId: '1:74155828355:ios:24b8d61913c143b364a7b6',
    messagingSenderId: '74155828355',
    projectId: 'dalel-e9613',
    storageBucket: 'dalel-e9613.appspot.com',
    iosBundleId: 'com.example.dalel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpdDAdmOj08eh7jvEgOZ1U_1eofUXkbX0',
    appId: '1:74155828355:ios:caa687e8f4da2ee064a7b6',
    messagingSenderId: '74155828355',
    projectId: 'dalel-e9613',
    storageBucket: 'dalel-e9613.appspot.com',
    iosBundleId: 'com.example.dalel.RunnerTests',
  );
}
