name: Android Fastlane Firebase App Distribution WorkFlow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  distribute_to_firebase:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout my repo code
        uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "temurin"

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
          working-directory: android

      - name: Upload APK to Firebase App Distribution
        env:
          FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
        run: |
          fastlane android firebase_distribute
          # You may need to replace 'fastlane distribute' with the appropriate Fastlane command for uploading to Firebase App Distribution
        working-directory: android
